"""High-priority Catalog V2 compatibility and collision overrides.

These definitions preserve established option labels while replacing legacy broad
regexes that can swallow a more precise V2 family.
"""

V2_OVERRIDE_QUESTION_CATALOG = [
    {
        "canonical_key": "race_ethnicity",
        "label": "Combined race and ethnicity",
        "category": "demographic",
        "sensitivity": "sensitive",
        "description": "A combined race-and-ethnicity disclosure question.",
        "patterns": [
            r"race and ethnicity",
            r"race/ethnicity",
            r"racial and ethnic",
            r"race or ethnicity",
            r"racial or ethnic",
        ],
        "setup_group": "Voluntary demographics",
        "suggested_answers": [
            "Black",
            "Middle Eastern or North African",
            "Asian",
            "Hispanic or Latino",
            "White",
            "Indigenous",
            "Two or more races",
            "Prefer not to answer",
        ],
        "fallback_suggestions": [
            "Black or African American",
            "Black or African descent",
            "African",
            "North African",
            "Middle Eastern",
            "Middle Eastern or North African (MENA)",
            "Arab",
            "West Asian or North African",
            "American Indian or Alaska Native",
            "Native Hawaiian or Other Pacific Islander",
            "Decline to self-identify",
        ],
        "default_mode": "decline",
    },
    {
        "canonical_key": "management_years",
        "label": "Years of management experience",
        "category": "qualification",
        "sensitivity": "standard",
        "description": "Years of direct people-management or supervisory experience.",
        "patterns": [
            r"how many years.{0,30}(?:management|supervisory|people management).{0,20}experience",
            r"years of (?:management|supervisory|people management) experience",
        ],
        "setup_group": "Qualifications",
        "suggested_answers": [],
        "fallback_suggestions": [],
        "default_mode": "ask_each_time",
    },
    {
        "canonical_key": "job_specific_experience",
        "label": "General relevant experience",
        "category": "qualification",
        "sensitivity": "standard",
        "description": "General relevant or overall professional experience when no named skill, tool, industry, or management subject is present.",
        "patterns": [
            r"relevant professional experience",
            r"overall professional experience",
            r"experience in a similar (?:role|position)",
            r"relevant experience for (?:this|the) (?:role|position)",
            r"years of overall experience",
        ],
        "setup_group": "Qualifications",
        "suggested_answers": [],
        "fallback_suggestions": [],
        "default_mode": "ask_each_time",
    },
    {
        "canonical_key": "language_proficiency",
        "label": "Language proficiency",
        "category": "qualification",
        "sensitivity": "standard",
        "description": "Proficiency in a human language, not software/tool proficiency.",
        "patterns": [
            r"language proficiency",
            r"languages? (?:do you|you) speak",
            r"fluency in (?:english|french|spanish|arabic|mandarin|cantonese|german|italian|portuguese|japanese|korean)",
            r"proficient in (?:english|french|spanish|arabic|mandarin|cantonese|german|italian|portuguese|japanese|korean)",
            r"(?:speak|read|write).{0,30}(?:english|french|spanish|arabic|mandarin|cantonese|german|italian|portuguese|japanese|korean)",
            r"maîtrise.*langue",
        ],
        "setup_group": "Qualifications",
        "suggested_answers": [
            "Native",
            "Fluent",
            "Professional working proficiency",
            "Intermediate",
            "Basic",
        ],
        "fallback_suggestions": [],
        "default_mode": "ask_each_time",
    },
]
