export const jobtomatikTheme = Object.freeze({
  colors: {
    background: '#081220',
    backgroundDeep: '#050B14',
    surface: '#111A2E',
    surfaceRaised: '#17243A',
    surfaceSoft: '#1A2A44',
    border: '#263A59',
    borderStrong: '#36537D',
    primary: '#2F6BFF',
    primaryHover: '#4D82FF',
    primaryLight: '#6AA7FF',
    foreground: '#F8FAFC',
    foregroundSoft: '#DCE4EF',
    muted: '#A8B3C7',
    mutedDim: '#71819C',
    accent: '#F2C14E',
    success: '#32C985',
    warning: '#F2C14E',
    danger: '#FF6574',
    info: '#6AA7FF',
  },
  typography: {
    family: 'Inter, Poppins, ui-sans-serif, system-ui, sans-serif',
    headingWeight: 700,
    displayWeight: 800,
    bodyWeight: 400,
    labelWeight: 600,
  },
  radius: {
    small: 10,
    medium: 14,
    large: 20,
    pill: 999,
  },
  spacing: {
    controlHeight: 42,
    mobileTabBarHeight: 68,
    sidebarWidth: 288,
  },
  shadows: {
    panel: '0 18px 55px rgba(0, 0, 0, 0.28)',
    glow: '0 0 0 1px rgba(106, 167, 255, 0.08), 0 14px 42px rgba(10, 37, 78, 0.34)',
    primary: '0 14px 30px rgba(47, 107, 255, 0.32)',
  },
})

export const statusTone = Object.freeze({
  new: 'info',
  discovered: 'info',
  queued: 'info',
  applied: 'primary',
  shortlisted: 'primary',
  interview: 'warning',
  assessment: 'warning',
  offer: 'success',
  hired: 'success',
  rejected: 'danger',
  failed: 'danger',
  withdrawn: 'neutral',
  archived: 'neutral',
})

export const categoryTone = Object.freeze({
  design: 'primary',
  engineering: 'info',
  development: 'info',
  marketing: 'warning',
  sales: 'success',
  product: 'primary',
  operations: 'neutral',
  data: 'info',
  finance: 'success',
  support: 'neutral',
})
